import { motion } from "framer-motion";
import Head from "next/head";
import React from "react";
import {useRecoilState, useRecoilValue} from "recoil";
import {backendUserState, userState} from "../../utils/atoms";
import { loginWithGoogle } from "../../firebase/firebase";

import Header from "../../components/Header";
import {useRouter} from "next/router";
import {getAuth} from "firebase/auth";
import {getUserFromBack} from "../api/userApi";

const Login: React.FC = () => {
  const router = useRouter();

  const handleGoogleLogin = async () => {
    try {
      const token = await loginWithGoogle();
      if (token) {
        await router.push("/");
      }
    } catch (error) {
      console.error("Google Login Error", error);
    }
  };

  return (
    <motion.div
      initial={{ opacity: 0 }}
      whileInView={{ opacity: 1 }}
      viewport={{ once: true }}
      className="h-screen overflow-hidden"
    >
      <Head>
        <title>Photoverse Sign In</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="icon"
          href="https://drive.google.com/uc?export=download&id=1eqWbbCrvcw6w6W-3eCEFkDu-9L2MbRaH"
        />
      </Head>
      <Header />
      <div className="flex flex-col items-center justify-center min-h-screen py-2 -m-56 px-14 text-center pt-60">
        <img
          className="w-70"
          src="https://www.pngmart.com/files/13/Instagram-Logo-PNG-Transparent.png"
          alt=""
        />
        <p className="font-xs italic">
          Sign in with your Google account to continue
        </p>
        <div className="mt-20">
          <div>
            <button
              className="p-3 bg-blue-500 rounded-lg text-white"
              onClick={() => handleGoogleLogin()}
            >
              Sign in with Google
            </button>
          </div>
        </div>
      </div>
    </motion.div>
  );
};
export default Login;
