import { motion } from "framer-motion";
import Head from "next/head";
import React, { useEffect, useState } from "react";

import Feed from "../components/Feed";
import Header from "../components/Header";
import {createUserInBack} from "./api/userApi";
import {useFirebaseAuth} from "../hooks/useFirebaseAuth";

const Home: React.FC = () => {
  const { user, backendUser } = useFirebaseAuth(); // firebase login 상태 전역 관리.
  const [userCreated, setUserCreated] = useState<boolean>(false);

  const getUserData = async () => {
    console.log("Recoil user: ", user);
    if (user && backendUser) {
        console.log("getUserData: ", user);
        console.log("User already created");
        setUserCreated(false);
    } else {
    console.log("User not found, creating user");
    setUserCreated(true);
    return;
    }
  };

  const createUser = async () => {
    if (userCreated && user && !backendUser) {
      try {
        await createUserInBack().finally(() => window.location.reload());
         // 유저 생성 후 백엔드 유저 정보를 갱신을 못함. 부득이하게 리로드.
      } catch (error) {
        console.error("Error creating user", error);
      }
    }
  };

  useEffect(() => {
    getUserData();
  }, [user, backendUser]);

  useEffect(() => {
    if (userCreated) {
      createUser();
    } else return;
  }, [userCreated]);

  return (
    <motion.div
      initial={{ opacity: 0 }}
      whileInView={{ opacity: 1 }}
      viewport={{ once: true }}
    >
      <Head>
        <title>Instagram Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="icon"
          href="https://i.postimg.cc/wjt4vkWx/pngwing-com-1.png"
        />
      </Head>
      <Header />
      <Feed user={backendUser} />
    </motion.div>
  );
};

export default Home;
